---
- name: Check project setup
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    configfolder: "{{ playbook_dir | dirname | dirname }}/config/{{ projectid }}"
  roles:
    - { role: namolabs.infra.fetchdata, tags: [always] }
    - name: namolabs.infra.generate_cloud_init
      tags: [always]
      vars:
        ansible_hashed_password: "test"
        ansible_ssh_authorized_key: "ssh-rsa dummy"
        vms: "{{ projectdata.vms }}"
