---
# Create Demo VM
- name: Create Demo VM
  hosts: pve02
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    configfolder: "{{ playbook_dir | dirname | dirname }}/config/{{ projectid }}"

  roles:
  - { role: namolabs.infra.fetchdata, tags: [ always ] }
  - role: namolabs.infra.generate_cloud_init
  - role: namolabs.infra.proxmox_create_vms
