---
- name: Test inventory role
  hosts: pve02
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    configfolder: "{{ playbook_dir | dirname | dirname }}/config/{{ projectid }}"
    project_state: "create"
  roles:
  - { role: namolabs.infra.fetchdata, tags: [ always ] }
  - name: namolabs.infra.inventory
    tags: [ always ]
    vars:
      vms: "{{ projectdata.vms }}"
